### ISSUE TITLE
Error Title: RuntimeException Due to Oversized RCON Packet

### ISSUE THREAD

**Issue by m3fri** [MemoriesOfTime/Nukkit-MOT#113]
🐞 Bug Feedback | BUG反馈
📝 Bug Description | BUG描述
An error occurred in the RCON (Remote Console) subsystem, resulting in a java.lang.RuntimeException. The specific issue is identified as a "Too big RCON packet: 134479886."

💻 OS and versions | 操作系统和核心版本
Nukkit-MOT master/8cac79a
Version: 1.20.40 (protocol 622)
Java: OracleJDK
Java version: 17
Platform: win10

```error
java.lang.RuntimeException: Too big RCON packet: 134479886
	at cn.nukkit.network.rcon.RCONPacket.<init>(RCONPacket.java:29) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.network.rcon.RCONServer.read(RCONServer.java:150) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.network.rcon.RCONServer.run(RCONServer.java:101) [Nukkit-MOT-SNAPSHOT.jar:?]

```

**Comment by BlusteryS** [comment]
+

**Comment by m3fri** [comment]
> Попробуйте изменить порт RCON

You can close this error, I wrote to you on discord, you just made it possible to change rcon ports. That was the problem
