### ISSUE TITLE
Error Title: InvocationTargetException in Entity Creation

### ISSUE THREAD

**Issue by m3fri** [MemoriesOfTime/Nukkit-MOT#114]
🐞 Bug Feedback | BUG反馈

📝 Bug Description | BUG描述
An error occurred during the creation of an entity, resulting in a java.lang.reflect.InvocationTargetException. The root cause of the issue is identified as a java.lang.NullPointerException in the EntityHuman class at line 211. The error is triggered when attempting to invoke the method getSkinData() on a null object, specifically on "this.skin."

🔍 Possible Cause | 可能的原因
The issue is associated with the EntityHuman class during entity initialization, specifically in the initEntity method (line 211). The NullPointerException occurs when attempting to access getSkinData() on a null "this.skin" object.

💻 OS and versions | 操作系统和核心版本
Nukkit-MOT master/8cac79a
Version: 1.20.40 (protocol 622)
Java: OracleJDK
Java version: 17
Platform: win10

```error
2023-11-29 22:48:50.599 [main] ERROR - Throwing
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedConstructorAccessor547.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at cn.nukkit.entity.Entity.createEntity(Entity.java:1021) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.entity.Entity.createEntity(Entity.java:982) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.entity.Entity.createEntity(Entity.java:977) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.blockentity.BlockEntitySpawner.onUpdate(BlockEntitySpawner.java:151) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:987) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at java.util.concurrent.ConcurrentLinkedQueue.bulkRemove(ConcurrentLinkedQueue.java:1004) [?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.removeIf(ConcurrentLinkedQueue.java:964) [?:?]
	at cn.nukkit.level.Level.doTick(Level.java:987) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1334) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tick(Server.java:1410) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1136) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.start(Server.java:1104) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:818) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:87) [Nukkit-MOT-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "cn.nukkit.entity.data.Skin.getSkinData()" because "this.skin" is null
	at cn.nukkit.entity.EntityHuman.initEntity(EntityHuman.java:211) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.entity.Entity.init(Entity.java:650) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.entity.Entity.<init>(Entity.java:518) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.entity.EntityLiving.<init>(EntityLiving.java:46) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.entity.EntityCreature.<init>(EntityCreature.java:13) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.entity.EntityHumanType.<init>(EntityHumanType.java:31) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.entity.EntityHuman.<init>(EntityHuman.java:87) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at com.smallaswater.npc.entitys.EntityRsNPC.<init>(EntityRsNPC.java:54) ~[?:?]
	at com.smallaswater.npc.entitys.EntityRsNPC.<init>(EntityRsNPC.java:50) ~[?:?]
	... 18 more
```

**Comment by lt-name** [comment]
Please create an issue in RsNPC repository
https://github.com/MemoriesOfTime/RsNPC
