### ISSUE TITLE
Error Title: ArrayIndexOutOfBoundsException in ResourcePackClientResponsePacket Decoding

### ISSUE THREAD

**Issue by m3fri** [MemoriesOfTime/Nukkit-MOT#115]
🐞 Bug Feedback | BUG反馈

📝 Bug Description | BUG描述
An error occurred while decoding a packet of type ResourcePackClientResponsePacket, resulting in a java.lang.ArrayIndexOutOfBoundsException. The issue is specifically located in the ResourcePackClientResponsePacket class at line 26. The error message indicates that the index 1 is out of bounds for an array of length 1.

🔍 Possible Cause | 可能的原因
The error is associated with decoding the ResourcePackClientResponsePacket and specifically trying to access an element at index 1 in an array that has a length of 1. This discrepancy in array length and the index being accessed is causing the ArrayIndexOutOfBoundsException.

💻 OS and versions | 操作系统和核心版本
Nukkit-MOT master/8cac79a
Version: 1.20.40 (protocol 622)
Java: OracleJDK
Java version: 17
Platform: win10

```error
2023-11-29 21:36:47.835 [Network Listener - #1] ERROR - Unable to decode packet
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at cn.nukkit.network.protocol.ResourcePackClientResponsePacket.decode(ResourcePackClientResponsePacket.java:26) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:250) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.onEncapsulated(RakNetPlayerSession.java:91) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:279) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:405) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:385) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:378) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:254) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.pipeline.ServerDatagramHandler.channelRead0(ServerDatagramHandler.java:43) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.pipeline.ServerDatagramHandler.channelRead0(ServerDatagramHandler.java:14) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.pipeline.ServerMessageHandler.channelRead0(ServerMessageHandler.java:34) [Nukkit-MOT-SNAPSHOT.jar:?]
	at com.nukkitx.network.raknet.pipeline.ServerMessageHandler.channelRead0(ServerMessageHandler.java:10) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:662) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:697) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:56) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:536) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Nukkit-MOT-SNAPSHOT.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Nukkit-MOT-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by lt-name** [comment]
It’s not like nk-mot’s problem
Please check if any plugin is trying to modify ResourcePackClientResponsePacket

**Comment by m3fri** [comment]
no, my server is completely vanilla
