### ISSUE TITLE
Error Title: IllegalArgumentException in Bug Report

### ISSUE THREAD

**Issue by m3fri** [MemoriesOfTime/Nukkit-MOT#118]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述
While attempting to send a bug report, an IllegalArgumentException occurred. The error message indicates that an empty string is not allowed. The issue is specifically located in the StringTag class at line 19. The stack trace further points to the CompoundTag class at line 118, BlockEntityItemFrame at line 133, NetworkChunkSerializer at lines 127 and 53, and finally to the Anvil class at line 112.

🔍 Possible Cause:
The error is related to attempting to create a StringTag with an empty string, which is not allowed according to the code in the StringTag class. This issue arises during the serialization of entities, particularly when dealing with BlockEntityItemFrame.

💻 OS and versions | 操作系统和核心版本
Nukkit-MOT master/8cac79a
Version: 1.20.40 (protocol 622)
Java: OracleJDK
Java version: 17
Platform: win10

```error
java.lang.IllegalArgumentException: Empty string not allowed
	at cn.nukkit.nbt.tag.StringTag.<init>(StringTag.java:19)
	at cn.nukkit.nbt.tag.CompoundTag.putString(CompoundTag.java:118)
	at cn.nukkit.blockentity.BlockEntityItemFrame.getSpawnCompound(BlockEntityItemFrame.java:133)
	at cn.nukkit.level.format.generic.serializer.NetworkChunkSerializer.serializeEntities(NetworkChunkSerializer.java:127)
	at cn.nukkit.level.format.generic.serializer.NetworkChunkSerializer.serialize(NetworkChunkSerializer.java:53)
	at cn.nukkit.level.format.anvil.Anvil.lambda$requestChunkTask$2(Anvil.java:112)
	...
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by PythonCircuit** [comment]
This happens when I use the /reload command more than once
