### ISSUE TITLE
Could not tick level "spawn"

### ISSUE THREAD

**Issue by BlusteryS** [MemoriesOfTime/Nukkit-MOT#235]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述
```
18:24:44 [ERROR] Could not tick level "spawn": java.lang.NullPointerException
17:51:31 [ERROR] Could not tick level "spawn": java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:581)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:996)
        at cn.nukkit.level.Level.tickChunks(Level.java:1323)
        at cn.nukkit.level.Level.doTick(Level.java:1029)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1345)
        at cn.nukkit.Server.tick(Server.java:1421)
        at cn.nukkit.Server.tickProcessor(Server.java:1141)
        at cn.nukkit.Server.start(Server.java:1109)
        at cn.nukkit.Server.<init>(Server.java:823)
        at cn.nukkit.Nukkit.main(Nukkit.java:87)
```

## 🔍 Steps to Reproduce | 复现方法
There were a lot of players on the server. At some point, the “spawn” world stopped loading and started producing the following errors

## ✅ Expected Behavior | 预期行为
Errors should not occur

## 📸 Screenshots / Video | 截图或视频
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/52814854/618f6b0c-dab6-44b2-a069-8e2cdf4c83f4)

## 💻 OS and versions | 操作系统和核心版本
```
18:27:30 [INFO ] #########################################
18:27:30 [INFO ] Nukkit-MOT
18:27:30 [INFO ] Build: master/d6655b1
18:27:30 [INFO ] Multiversion: Up to version 1.20.70
18:27:30 [INFO ] #########################################
```

* Java: OracleJDK
* Java version: 21

**Comment by StefanFox-Dev** [comment]
I just caught the same mistake)))

**Comment by StefanFox-Dev** [comment]
The problem is that if you spawn Vizer, there will be such an error. Fix: `/kill @e`
