### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by StefanFox-Dev** [MemoriesOfTime/Nukkit-MOT#253]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

```10:48:21 [INFO ] <maengrafter> нет на 1 базе нашей
10:48:28 [INFO ] <Axeo7025> Мандарин. Давай переговоры
10:48:29 [WARN ] MissingWharf829 moved too far (212.18)
10:48:29 [WARN ] MissingWharf829 moved too far (209.55)
10:48:29 [WARN ] MissingWharf829 moved too far (203.70)
10:48:29 [WARN ] MissingWharf829 moved too far (197.14)
10:48:29 [WARN ] MissingWharf829 moved too far (184.21)
10:48:29 [WARN ] MissingWharf829 moved too far (176.72)
10:48:29 [WARN ] MissingWharf829 moved too far (169.62)
10:48:29 [WARN ] MissingWharf829 moved too far (162.83)
10:48:29 [WARN ] MissingWharf829 moved too far (156.32)
10:48:29 [WARN ] MissingWharf829 moved too far (150.03)
10:48:29 [WARN ] MissingWharf829 moved too far (144.00)
10:48:29 [WARN ] MissingWharf829 moved too far (138.27)
10:48:29 [WARN ] MissingWharf829 moved too far (132.92)
10:48:29 [WARN ] MissingWharf829 moved too far (128.06)
10:48:31 [WARN ] maengrafter moved too far (152.38)
10:48:31 [WARN ] maengrafter moved too far (149.19)
10:48:31 [WARN ] maengrafter moved too far (152.38)
10:48:31 [WARN ] maengrafter moved too far (149.19)
10:48:31 [WARN ] maengrafter moved too far (145.47)
10:48:31 [WARN ] maengrafter moved too far (141.49)
10:48:31 [WARN ] maengrafter moved too far (137.42)
10:48:31 [WARN ] maengrafter moved too far (133.35)
10:48:31 [WARN ] maengrafter moved too far (129.31)
10:48:31 [WARN ] danillalol1 moved too far (287.60)
10:48:31 [WARN ] danillalol1 moved too far (280.90)
10:48:31 [WARN ] danillalol1 moved too far (276.42)
10:48:31 [WARN ] danillalol1 moved too far (271.55)
10:48:31 [WARN ] danillalol1 moved too far (263.02)
10:48:31 [WARN ] danillalol1 moved too far (254.34)
10:48:31 [WARN ] danillalol1 moved too far (245.68)
10:48:31 [WARN ] danillalol1 moved too far (231.18)
10:48:31 [WARN ] danillalol1 moved too far (223.00)
10:48:31 [WARN ] danillalol1 moved too far (215.05)
10:48:31 [WARN ] danillalol1 moved too far (207.21)
10:48:31 [WARN ] danillalol1 moved too far (199.39)
10:48:31 [WARN ] danillalol1 moved too far (191.57)
10:48:31 [WARN ] danillalol1 moved too far (183.74)
10:48:31 [WARN ] danillalol1 moved too far (175.96)
10:48:31 [WARN ] danillalol1 moved too far (169.27)
10:48:31 [WARN ] danillalol1 moved too far (163.35)
10:48:31 [WARN ] danillalol1 moved too far (160.01)
10:48:31 [WARN ] danillalol1 moved too far (158.02)
10:48:31 [WARN ] danillalol1 moved too far (156.16)
10:48:31 [WARN ] danillalol1 moved too far (154.51)
10:48:31 [WARN ] danillalol1 moved too far (153.18)
10:48:31 [WARN ] danillalol1 moved too far (152.02)
10:48:31 [WARN ] danillalol1 moved too far (151.38)
10:48:43 [INFO ] <RealMaxHack> данил
10:49:00 [WARN ] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.socket.ChannelOutputShutdownException: Channel output shutdown
        at io.netty.channel.AbstractChannel$AbstractUnsafe.shutdownOutput(AbstractChannel.java:650) ~[n.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.handleWriteError(AbstractChannel.java:953) ~[n.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:933) ~[n.jar:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354) ~[n.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) ~[n.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) ~[n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921) ~[n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) ~[n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) ~[n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.server.RakChildDatagramHandler.flush(RakChildDatagramHandler.java:68) ~[n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925) ~[n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) ~[n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) ~[n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.internalFlush(RakSessionCodec.java:466) ~[n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.onTick(RakSessionCodec.java:425) ~[n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.tryTick(RakSessionCodec.java:393) ~[n.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[n.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[n.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[n.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[n.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[n.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[n.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[n.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[n.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[n.jar:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.nio.DirectByteBuffer.duplicate(DirectByteBuffer.java:284) ~[?:?]
        at java.nio.DirectByteBuffer.duplicate(DirectByteBuffer.java:42) ~[?:?]
        at io.netty.buffer.UnpooledDirectByteBuf.internalNioBuffer(UnpooledDirectByteBuf.java:625) ~[n.jar:?]
        at io.netty.buffer.UnpooledDirectByteBuf.internalNioBuffer(UnpooledDirectByteBuf.java:619) ~[n.jar:?]
        at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:293) ~[n.jar:?]
        at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143) ~[n.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) [n.jar:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354) [n.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) [n.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) [n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921) [n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) [n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) [n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.server.RakChildDatagramHandler.flush(RakChildDatagramHandler.java:68) [n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925) [n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) [n.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) [n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.internalFlush(RakSessionCodec.java:466) [n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.onTick(RakSessionCodec.java:425) [n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.tryTick(RakSessionCodec.java:393) [n.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec$$Lambda/0x00007fc7e0785f88.run(Unknown Source) [n.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [n.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) [n.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) [n.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) [n.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [n.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) [n.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [n.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [n.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [n.jar:?]
        at java.lang.Thread.runWith(Thread.java:1596) [?:?]
        ... 1 more
> 2024-04-29 10:49:00,597 main ERROR An exception occurred processing Appender Console org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.OutOfMemoryError: Java heap space
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.throwing(AbstractLogger.java:2254)
        at org.apache.logging.log4j.spi.AbstractLogger.throwing(AbstractLogger.java:2235)
        at cn.nukkit.Nukkit.main(Nukkit.java:89)
Caused by: java.lang.OutOfMemoryError: Java heap space```

## 🔍 Steps to Reproduce | 复现方法

<!-- 
Write below how we can repeat this.
下面写下我们如何重复这一点。
-->

1. Go to '...' ✍
2. Interact with '....' ✍
3. Perform action '....' ✍
4. See unexpected behavior 😕 ✍

## ✅ Expected Behavior | 预期行为

<!--
A description that is both clear and succinct, outlining your anticipated outcome.
您可通过简洁的描述概述预期行为
-->

## 📸 Screenshots / Video | 截图或视频

<!--
For a clearer understanding of your issues, it's recommended to provide screenshots or videos. Without visual aids, your issues might remain unresolved.
为了更好地理解您的问题，请附带截图或视频。如果没有图像辅助，您的问题可能无法得到解决。
-->

## 💻 OS and versions | 操作系统和核心版本

<!--
Execute the `version` command in your game or on the server console; this command will provide the necessary information.
请在游戏或服务器控制台上执行`version`指令，该指令将提供所需的信息。
-->

* Version: 1.20.80
* Java: OracleJDK <!-- Delete the ones that don't fit / 删除不合适的 -->
* Java version: 21 <!-- Default / 默认 -->
* Game version: Android/iOS/Win10/Xbox/PS4/Switch <!-- Delete the ones that don't fit / 删除不合适的 -->

## 💡 Possible Solution | 可能的解决方案

<!-- 
If you have any initial thoughts on how to solve this bug, please share them here. 
如果你对BUG有什么好的解决想法等，可以在此分享你的观点
-->

I think that...

## 📝 Logs | 日志

<!-- 
If you encounter an error in your console, you can share it as a message under the "ERROR" category. Just replace the word "ERROR" and then paste the error details into the message. 
如果在控制台上发现的错误日志，你可以将其复制黏贴至下面的内容栏中以便我们更好的进行分析和描述问题细节
-->

<!--
Use https://hastebin.com for big logs or dumps
对于体积过大的日志和dump文件，请使用https://hastebin.com
-->

Debug link (optional): ✍  
Spark link (optional): ✍

```error
ERROR
```

**Comment by lt-name** [comment]
What is the core version? You can use the /ver command to view
