### ISSUE TITLE
Player in the nether faced NullPointerException error in chunks and cannot join the game

### ISSUE THREAD

**Issue by glorydark** [MemoriesOfTime/Nukkit-MOT#31]
# 报错
``` log
03:34:14 [FATAL] Exception in asynchronous task
java.lang.NullPointerException: Cannot invoke "cn.nukkit.level.format.generic.BaseFullChunk.getBlockId(int, int, int)" because "chunk" is null
        at cn.nukkit.level.generator.structure.StructurePiece.fillColumnDown(StructurePiece.java:259) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.structure.NetherBridgePieces$CastleSmallCorridorPiece.postProcess(NetherBridgePieces.java:890) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.structure.StructureStart.lambda$postProcess$0(StructureStart.java:39) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at cn.nukkit.level.generator.structure.StructureStart.postProcess(StructureStart.java:39) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.populator.nether.PopulatorNetherFortress.populate(PopulatorNetherFortress.java:47) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.Nether.populateChunk(Nether.java:146) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:109) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:50) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:45) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:22) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by java.lang.NullPointerException: Cannot invoke "cn.nukkit.level.format.generic.BaseFullChunk.getBlockId(int, int, int)" because "chunk" is null
        at cn.nukkit.level.generator.structure.StructurePiece.fillColumnDown(StructurePiece.java:259)
        at cn.nukkit.level.generator.structure.NetherBridgePieces$CastleSmallCorridorPiece.postProcess(NetherBridgePieces.java:890)
        at cn.nukkit.level.generator.structure.StructureStart.lambda$postProcess$0(StructureStart.java:39)
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
        at cn.nukkit.level.generator.structure.StructureStart.postProcess(StructureStart.java:39)
        at cn.nukkit.level.generator.populator.nether.PopulatorNetherFortress.populate(PopulatorNetherFortress.java:47)
        at cn.nukkit.level.generator.Nether.populateChunk(Nether.java:146)
        at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:109)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:50)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:55)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:45)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

# 如何复现
https://github.com/MemoriesOfTime/Nukkit-MOT/assets/61799945/c906d2f3-0148-4f0d-8e54-7ac14cdb9a46
当你看到卡的一瞬间，后台就已经在报错了。
如果出现此bug的话，那么就算重启也无济于事了。

**Comment by glorydark** [comment]
[corrupts_nether.zip](https://github.com/MemoriesOfTime/Nukkit-MOT/files/12448723/corrupts_nether.zip)

**Comment by BlusteryS** [comment]
Try to use #32
